# Generated by Django 3.0 on 2020-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlinktoalimentstable',
            name='aliment_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userlinktoalimentstable',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
